import Link from "next/link";
import { ArrowRight, Blocks, FileCheck2, GraduationCap, Route } from "lucide-react";

import { MarketingBreadcrumbs } from "@/components/marketing/marketing-breadcrumbs";
import { Container, Section } from "@/components/shared/container";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { breadcrumbJsonLd, CONTENT_UPDATED_AT, ORGANIZATION_ID, pageMetadata, safeJsonLd, SITE_URL, WEBSITE_ID } from "@/lib/seo";

export const metadata = pageMetadata({ title: "About Ropes—Practical AI Learning for Independent Work", description: "Ropes helps working professionals combine existing expertise with AI systems, practical builds, portfolio evidence, and professional application.", path: "/about" });

export default function AboutPage() {
  const structured = [{ "@context": "https://schema.org", "@type": "AboutPage", name: "About Ropes", url: `${SITE_URL}/about`, dateModified: CONTENT_UPDATED_AT, isPartOf: { "@id": WEBSITE_ID }, mainEntity: { "@type": "EducationalOrganization", "@id": ORGANIZATION_ID, name: "Ropes", url: SITE_URL, areaServed: "IN", slogan: "Learn the ropes. Go independent.", description: "Ropes helps working professionals combine existing expertise with AI systems, practical builds, portfolio evidence, and professional application." } }, breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "About Ropes", path: "/about" }])];
  return <div>{structured.map((item, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(item) }} />)}<Section className="bg-primary text-primary-foreground"><Container><MarketingBreadcrumbs items={[{ label: "Home", href: "/" }, { label: "About Ropes" }]} /><span className="text-micro font-semibold uppercase tracking-wide text-accent">Who Ropes is for</span><h1 className="mt-4 max-w-4xl font-heading text-h1 font-bold">AI learning built around the experience you already have</h1><p className="mt-5 max-w-3xl text-body-lg text-white/75">Ropes is a professional learning platform for people who want to build practical AI capability and apply it to real work—inside a job, as a freelancer or consultant, or while exploring a one-person business.</p></Container></Section><Section><Container><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[
    { icon: GraduationCap, title: "Learn", text: "Understand the concepts, tools, decisions, and failure modes behind the capability." },
    { icon: Blocks, title: "Build", text: "Create a concrete system or professional artifact rather than stopping at passive lessons." },
    { icon: FileCheck2, title: "Prove", text: "Document the problem, approach, tests, trade-offs, outcome, and limitations." },
    { icon: Route, title: "Apply", text: "Connect the capability to a professional function, market problem, or independent-work path." },
  ].map((item) => <Card key={item.title}><CardHeader><item.icon className="mb-2 size-6 text-accent-600" /><CardTitle>{item.title}</CardTitle><CardDescription>{item.text}</CardDescription></CardHeader></Card>)}</div><div className="mx-auto mt-14 max-w-3xl"><h2 className="font-heading text-h2 font-bold">What Ropes does—and does not promise</h2><div className="mt-5 space-y-4 text-lg leading-8 text-muted-foreground"><p>Ropes teaches structured skills through modules, AI mentor support, professional playbooks, exercises, diagnostics, project work, and portfolio-oriented outcomes. The exact experience depends on the course.</p><p>Ropes does not guarantee employment, clients, revenue, or salary replacement. Independent work depends on capability, market demand, positioning, execution, trust, timing, and factors outside any course provider’s control.</p><p>Private learner profiles, submissions, assessments, conversations, and portfolio work remain behind authentication. Public project briefs explain capabilities without publishing private learner data.</p></div><div className="mt-8 flex flex-wrap gap-3"><Button asChild variant="accent"><Link href="/courses">Explore courses <ArrowRight className="size-4" /></Link></Button><Button asChild variant="outline"><Link href="/resources">Read public resources</Link></Button></div></div></Container></Section></div>;
}
