import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CheckCircle2 } from "lucide-react";

import { MarketingBreadcrumbs } from "@/components/marketing/marketing-breadcrumbs";
import { Container, Section } from "@/components/shared/container";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { breadcrumbJsonLd, pageMetadata, safeJsonLd } from "@/lib/seo";

export const metadata = pageMetadata({ title: "AI Pathways for Working Professionals—Technical and Non-Technical", description: "See how sales, marketing, operations, finance, HR, consulting, and technical professionals can combine existing expertise with AI systems and portfolio proof.", path: "/for-professionals", keywords: ["AI for working professionals", "AI for non technical professionals", "AI training for professionals", "career change with AI"] });

const pathways = [
  { function: "Sales & business development", advantage: "Buyer context, qualification judgment, pipeline language", builds: "Account research, lead qualification, proposal, and CRM workflows", courses: ["ai-agents-with-n8n-no-code", "agentic-ai"] },
  { function: "Marketing & content", advantage: "Audience, campaign, brand, and channel judgment", builds: "Research, campaign operations, content transformation, and reporting systems", courses: ["ai-agents-with-n8n-no-code", "generative-ai-genai"] },
  { function: "Operations & supply chain", advantage: "Process, exception, handoff, and control knowledge", builds: "Workflow automation, SOP assistants, reporting, triage, and approval systems", courses: ["ai-agents-with-n8n-no-code", "aiops"] },
  { function: "Finance & analytics", advantage: "Controls, reconciliations, reporting, and decision context", builds: "Analysis pipelines, reporting workflows, forecasting support, and grounded document systems", courses: ["data-science-with-generative-ai", "data-science-ai-ml"] },
  { function: "HR, learning & administration", advantage: "Policy, employee journey, communication, and governance context", builds: "Onboarding, policy knowledge, intake, document, and support workflows", courses: ["ai-agents-with-n8n-no-code", "ai-product-management"] },
  { function: "Consulting & project management", advantage: "Discovery, stakeholder alignment, structured delivery, and change management", builds: "Research, discovery, decision, documentation, and client-delivery systems", courses: ["ai-product-management", "agentic-ai"] },
  { function: "Software, IT & engineering", advantage: "Systems, integration, reliability, and production context", builds: "Agents, AI applications, cloud systems, MLOps, LLMOps, testing, and security", courses: ["agentic-ai-development-with-langchain-langgraph", "ai-engineering-for-forward-deployed-engineer"] },
  { function: "Data, QA & product", advantage: "Evidence, evaluation, quality, experimentation, and user-outcome thinking", builds: "Analytics, evaluation suites, product specifications, model pipelines, and release controls", courses: ["ai-llm-testing", "ai-product-management"] },
];

export default function ForProfessionalsPage() {
  const breadcrumb = breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "Resources", path: "/resources" }, { name: "For professionals", path: "/for-professionals" }]);
  return <div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(breadcrumb) }} />
    <Section className="bg-primary bg-mesh-hero bg-noise text-primary-foreground"><Container><MarketingBreadcrumbs items={[{ label: "Home", href: "/" }, { label: "Resources", href: "/resources" }, { label: "For professionals" }]} /><span className="text-micro font-semibold uppercase tracking-wide text-accent">Your experience is an input, not baggage</span><h1 className="mt-4 max-w-4xl font-heading text-h1 font-bold">Combine what you already know with AI, systems, and delivery</h1><p className="mt-5 max-w-3xl text-body-lg text-white/75">Ropes is for technical and non-technical professionals. The right path depends on the business problems you understand, the systems you want to build, and the level of technical depth those systems require.</p></Container></Section>
    <Section><Container className="grid gap-8 lg:grid-cols-[1.1fr_0.9fr]"><div><h2 className="font-heading text-h2 font-bold">You do not have to erase your career</h2><p className="mt-4 text-lg leading-8 text-muted-foreground">Domain experience gives you vocabulary, workflow context, quality judgment, and an understanding of exceptions. AI and automation can extend that advantage into a new professional capability when you also learn system design, testing, proof, and client delivery.</p></div><Card className="border-accent/30 bg-accent-50"><CardHeader><BriefcaseBusiness className="mb-2 size-6 text-accent-600" /><CardTitle>The capability equation</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{["Existing professional expertise", "AI and automation leverage", "A practical system", "Portfolio evidence", "A defined professional application"].map((item, index) => <div key={item} className="flex items-center gap-3 text-sm"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-primary text-xs font-bold text-white">{index + 1}</span>{item}</div>)}</CardContent></Card></Container></Section>
    <Section className="bg-muted/40"><Container><h2 className="font-heading text-h2 font-bold">Function → advantage → build</h2><p className="mt-3 max-w-3xl text-muted-foreground">These are useful starting hypotheses, not automatic service ideas. Validate the buyer, problem, constraints, and required competence before offering work.</p><div className="mt-8 overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-primary text-white"><tr><th className="p-4">Professional function</th><th className="p-4">Existing advantage</th><th className="p-4">AI-enabled builds</th><th className="p-4">Relevant paths</th></tr></thead><tbody>{pathways.map((path) => <tr key={path.function} className="border-t border-border align-top"><td className="p-4 font-heading font-semibold">{path.function}</td><td className="p-4 text-muted-foreground">{path.advantage}</td><td className="p-4 text-muted-foreground">{path.builds}</td><td className="p-4"><div className="flex flex-col gap-2">{path.courses.map((slug) => <Link key={slug} href={`/courses/${slug}`} className="text-primary underline underline-offset-4">{slug.replace(/-/g, " ")}</Link>)}</div></td></tr>)}</tbody></table></div></Container></Section>
    <Section><Container><div className="mb-8 max-w-2xl"><h2 className="font-heading text-h2 font-bold">Choose depth based on the work</h2><p className="mt-3 text-muted-foreground">Non-technical does not mean unskilled, and technical does not automatically mean client-ready.</p></div><div className="grid gap-5 md:grid-cols-2"><Card><CardHeader><CardTitle>Non-technical and no-code paths</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{["Workflow discovery and process mapping", "No-code orchestration and data handling", "AI-assisted research and knowledge systems", "Evaluation, privacy, approvals, and handover"].map((item) => <div key={item} className="flex gap-2.5 text-sm"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-success" />{item}</div>)}<Button asChild variant="outline" className="mt-3 w-fit"><Link href="/freelancing-without-coding">Explore the no-code path <ArrowRight className="size-4" /></Link></Button></CardContent></Card><Card><CardHeader><CardTitle>Technical and production paths</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{["Application and agent engineering", "Cloud architecture and integrations", "MLOps, LLMOps, testing, and observability", "AI security and production reliability"].map((item) => <div key={item} className="flex gap-2.5 text-sm"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-success" />{item}</div>)}<Button asChild variant="outline" className="mt-3 w-fit"><Link href="/courses">Compare technical tracks <ArrowRight className="size-4" /></Link></Button></CardContent></Card></div></Container></Section>
    <Section className="bg-primary text-primary-foreground"><Container className="flex flex-col items-start justify-between gap-5 md:flex-row md:items-center"><div><h2 className="font-heading text-h3 font-bold">Start with a problem you understand</h2><p className="mt-2 max-w-2xl text-white/70">Then learn the system, build proof, and decide whether the capability fits employment, consulting, freelancing, or a one-person business.</p></div><Button asChild variant="accent"><Link href="/turn-skills-into-freelance-services">Turn expertise into a service <ArrowRight className="size-4" /></Link></Button></Container></Section>
  </div>;
}
