import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Layers3, Route, Wrench } from "lucide-react";

import { MarketingBreadcrumbs } from "@/components/marketing/marketing-breadcrumbs";
import { Container, Section } from "@/components/shared/container";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ACQUISITION_PAGES, SKILL_GUIDES } from "@/lib/acquisition-content";
import { breadcrumbJsonLd, pageMetadata, safeJsonLd } from "@/lib/seo";

export const metadata = pageMetadata({ title: "AI Freelancing & Independent Work Resources", description: "Practical Ropes guides for AI freelancing, professional side income, solopreneurship, no-code work, portfolio projects, and client-ready AI skills.", path: "/resources" });

const pillars = ["ai-freelancing", "side-hustle-for-working-professionals", "solopreneur-with-ai", "turn-skills-into-freelance-services", "ai-automation-freelancing", "freelancing-without-coding"];

export default function ResourcesPage() {
  const breadcrumb = breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "Resources", path: "/resources" }]);
  return <div>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(breadcrumb) }} />
    <Section className="bg-primary bg-mesh-hero bg-noise text-primary-foreground"><Container><MarketingBreadcrumbs items={[{ label: "Home", href: "/" }, { label: "Resources" }]} /><span className="text-micro font-semibold uppercase tracking-wide text-accent">Search → learn → build → apply</span><h1 className="mt-4 max-w-4xl font-heading text-h1 font-bold">Resources for turning professional knowledge into AI-powered work</h1><p className="mt-5 max-w-3xl text-body-lg text-white/75">Start with your real goal, understand the skill, inspect what a credible project looks like, and then choose the course that develops the capability.</p></Container></Section>
    <Section><Container><div className="mb-9 max-w-2xl"><h2 className="font-heading text-h2 font-bold">Choose the question you are trying to answer</h2><p className="mt-3 text-muted-foreground">These guides are deliberately broad enough to be useful and specific enough to lead to a real build. They are not keyword-variation pages.</p></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{pillars.map((slug) => { const page = ACQUISITION_PAGES[slug]; return <Link key={slug} href={`/${slug}`} className="group"><Card className="h-full transition hover:-translate-y-1 hover:shadow-lifted"><CardHeader><Route className="mb-2 size-5 text-accent-600" /><CardTitle className="text-lg">{page.title}</CardTitle><CardDescription>{page.directAnswer}</CardDescription></CardHeader><CardContent className="flex items-center gap-2 text-sm font-semibold text-primary">Read the guide <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></CardContent></Card></Link>; })}</div></Container></Section>
    <Section className="bg-muted/40"><Container><div className="mb-9"><h2 className="font-heading text-h2 font-bold">Understand the capability</h2><p className="mt-3 max-w-2xl text-muted-foreground">Each skill guide connects a definition to portfolio evidence, professional application, and the relevant curriculum.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.values(SKILL_GUIDES).map((skill) => <Link key={skill.slug} href={`/resources/skills/${skill.slug}`} className="rounded-xl border border-border bg-card p-5 transition hover:border-accent/50 hover:shadow-card"><Layers3 className="size-5 text-accent-600" /><h3 className="mt-3 font-heading font-semibold">{skill.name}</h3><p className="mt-2 line-clamp-3 text-sm text-muted-foreground">{skill.definition}</p></Link>)}</div></Container></Section>
    <Section><Container className="grid gap-5 md:grid-cols-3"><Link href="/for-professionals"><Card className="h-full"><CardHeader><BriefcaseBusiness className="mb-2 size-5 text-accent-600" /><CardTitle>Start from your professional function</CardTitle><CardDescription>See how sales, marketing, operations, finance, HR, consulting, and technical knowledge can connect to AI systems.</CardDescription></CardHeader><CardContent className="text-sm font-semibold text-primary">Explore function pathways →</CardContent></Card></Link><Link href="/resources/projects"><Card className="h-full"><CardHeader><Wrench className="mb-2 size-5 text-accent-600" /><CardTitle>Inspect portfolio project briefs</CardTitle><CardDescription>See the problem, approach, deliverable, skill, and professional application—without exposing learner submissions.</CardDescription></CardHeader><CardContent className="text-sm font-semibold text-primary">Browse project briefs →</CardContent></Card></Link><Link href="/courses"><Card className="h-full bg-primary text-primary-foreground"><CardHeader><Layers3 className="mb-2 size-5 text-accent" /><CardTitle>Compare Ropes courses</CardTitle><CardDescription className="text-white/65">Review the real curriculum, module builds, professional capability, and course price.</CardDescription></CardHeader><CardContent className="text-sm font-semibold text-accent">Browse courses →</CardContent></Card></Link></Container></Section>
  </div>;
}
